<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/04MakeArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

Este método de NumPy nos permite generar arrays sin definir previamente una lista.


In [ ]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Un tercer argumento permite definir un tamaño de paso
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#np.zeros() Nos permite definir estructuras o esquemas
np.zeros(3)
np.zeros((10,5))#(filas,columnas)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#De igual manera, tenemos np.ones()
np.ones(3)

array([1., 1., 1.])

In [ ]:
#np.linspace() Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá
np.linspace(0, 10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#También podemos crear una matriz con una diagonal de 1 y el resto de 0
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Otro método importante es generar números aleatorios
np.random.rand()

0.7259757573610758

In [ ]:
#También se pueden generar vectores
np.random.rand(4)

array([0.9488456 , 0.66499835, 0.38878938, 0.08867814])

In [ ]:
#Y a su vez generar matrices
np.random.rand(4,4)

array([[0.94593517, 0.42670419, 0.38074496, 0.48414585],
       [0.21037096, 0.22882054, 0.04425334, 0.59443865],
       [0.66816357, 0.22497557, 0.13282148, 0.40873121],
       [0.0416009 , 0.12251237, 0.45343264, 0.89574812]])

In [ ]:
#NumPy nos permite también generar números enteros. En este caso números enteros entre el 1 y 14
np.random.randint(1,155)

112

In [ ]:
#También podemos llevarlos a una estructura definida
np.random.randint(1,15, (3,3))

array([[ 3,  1,  4],
       [ 6,  5, 13],
       [ 2, 14,  1]])