<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/05Shape_and_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Hay 2 funciones muy importantes de los arreglos (Shape y Reshape). La forma de un arreglo nos va a decir con que estructura se está trabajando (tamaño, manipular, ingresar).

In [ ]:
#Shape
#Indica la forma del arreglo
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [ ]:
arr

array([[7, 8],
       [8, 8],
       [5, 5]])

In [ ]:
#Reshape
#transforma el arreglo mientras se mantengan los elementos
arr.reshape(1,6)


array([[7, 8, 8, 8, 5, 5]])

In [ ]:
arr.reshape(2,3)

array([[7, 8, 8],
       [8, 5, 5]])

In [ ]:
np.reshape(arr,(1,6))

array([[7, 8, 8, 8, 5, 5]])

In [ ]:
#Se puede hacer un reshape como lo haría C
np.reshape(arr,(2,3), 'C')

array([[7, 8, 8],
       [8, 5, 5]])

In [ ]:
#También se puede hacer reshape a como lo haría Fortran
np.reshape(arr,(2,3), 'F')

array([[7, 5, 8],
       [8, 8, 5]])

In [ ]:
#Además, existe la opción de hacer reshape según como esté optimizado nuestro sistema. En este caso es como en C
np.reshape(arr,(2,3), 'A')

array([[7, 8, 8],
       [8, 5, 5]])

In [ ]:
'''
Si tienes un (3,3) no lo puedes pasar a (4,2). 
No respeta los 9 elementos del array original
'''

'\nSi tienes un (3,3) no lo puedes pasar a (4,2). \nNo respeta los 9 elementos del array original\n'