<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/06Funciones_Principales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 20, 10)
arr

array([17,  7, 15, 14, 19, 18, 18,  4, 12,  6])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[17,  7, 15, 14, 19],
       [18, 18,  4, 12,  6]])

In [ ]:
#.max Para el máximo
arr.max()


19

In [ ]:
matriz.max()

19

In [ ]:
#Podemos regresar los máximos de cada fila o columna especificando el eje
#0-> columnas, 1-> filas 
matriz.max(1) 

array([19, 18])

In [ ]:
matriz.max(0)

array([18, 18, 15, 14, 19])

In [ ]:
#También tenemos .argmax() que nos devuelve la posición del elemento
arr.argmax()

4

In [ ]:
#En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas
matriz.argmax(0)

array([1, 1, 0, 0, 0])

In [ ]:
#De forma análoga tenemos .min()
arr.min()

4

In [ ]:
arr.argmin()

7

In [ ]:
matriz.min(0) 

array([17,  7,  4, 12,  6])

In [ ]:
matriz.argmin(1)

array([1, 2])

In [ ]:
#Podemos saber la distancia entre el valor más bajo con el más alto
arr.ptp()

15

In [ ]:
matriz.ptp(0)

array([ 1, 11, 11,  2, 13])

##Análisis estadístico
###Ordenar los elementos:

In [ ]:
arr.sort()

In [ ]:
arr

array([ 4,  6,  7, 12, 14, 15, 17, 18, 18, 19])

In [ ]:
np.percentile(arr, 50)

14.5

In [ ]:
np.median(arr)

14.5

In [ ]:
#Desviación estándar:
np.std(arr)

5.2345009313209605

In [ ]:
#Varianza:
np.var(arr)

27.4

In [ ]:
#Promedio:
np.mean(arr)

13.0

In [ ]:
#Lo mismo aplica para las matrices
np.median(matriz, 1)

array([ 7., 18.])

##Concatenación
###Se pueden unir dos arrays

In [ ]:
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])

In [ ]:
np.concatenate((a,b), axis = 0)

ValueError: ignored

In [ ]:
#El error anterior es debido a que ‘a’ tiene 2 dimensiones, mientras que ‘b’ tiene 1.
a.ndim


2

In [ ]:
b.ndim 

1

In [ ]:
#Debemos poner ‘b’ en 2 dimensiones también
b = np.expand_dims(b, axis = 0)

In [ ]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
'''
La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)
'''

'\nLa transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)\n'

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])