<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/07the_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
'''
.copy() nos permite copiar un array de NumPy en otra variable de tal
forma que al modificar el nuevo array los cambios no se vean reflejados en array original.
'''
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Tomamos un trozo del array original
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_de_arr = arr[0:6]

In [ ]:
#Queremos pasar todas nuestras variables a 0
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
#Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.
#Con .copy() creamos una copia para no dañar nuestro array original
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])