<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/08Condiciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Las condiciones nos permiten hacer consultas más específicas.

In [ ]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
#Regresa un array de booleanos dónde la condición se cumple.
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
#Regresa los valores para dónde la condiciones True
arr[indices_cond] 

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
#Múltiples condiciones
arr[(arr > 5) & (arr < 9)] 

array([6, 7, 8], dtype=int8)

In [ ]:
#Modificar los valores que cumplan la condición
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)