<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/09Operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Existen diferentes operaciones que se pueden usar para los arrays de NumPy.

In [ ]:
lista = [1,2]

In [ ]:
#Una lista de Python entiende que quieres duplicar los datos. No es lo que buscamos
lista * 2 

[1, 2, 1, 2]

In [ ]:
#Pero Numpy lo entiende mucho mejor
arr = np.arange(0,10)
arr2 = arr.copy()

In [ ]:
#Ahora multiplicamos por un escalar
arr * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#Operación suma de vectores
arr + 2 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
'''
División con un vector
Como en este caso la primera posición del array es 0, muestra un error pero, no detiene el proceso.
'''

1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
#Elevar a un vector:
arr**2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
#Sumar dos arrays de igual dimensiones las hace elemento por elemento
arr + arr2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#Lo mismo aplica para matrices
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#Una operación importante es la de multiplicación de matrices, aquí dos formas de hacerla
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])