<a href="https://colab.research.google.com/github/danieldrako/Manipulacion-Transformacion-Datos-Pandas-NumPy/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#Volvemos nuestra lista, un array
arr = np.array(lista)

In [5]:
#Una matriz son varios Vectores o listas agrupadas una encima de la otra, es como una tabla de Excel
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#El indexado nos permite acceder a los elementos de los array y matrices. Los elementos se empiezan a contar desde 0.
arr[0]

1

In [7]:
#Es posible operar directamente con los elementos
arr[0] + arr[5]

7

In [9]:
#En el caso de las matrices, al indexar una posición se regresa el array de dicha posición
matriz[0]

array([1, 2, 3])

In [10]:
'''
Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.
Nota: El primer elemento selecciona las filas, el segundo elemento las columnas
'''

matriz[0, 2]

3

##Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5.

In [12]:
arr[1:6]


array([2, 3, 4, 5, 6])

In [13]:
#Si no se ingresa el valor de inicio, se toma el inicio como la posición 0
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [14]:
#En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])


###También se puede trabajar por pasos.

En este ejemplo de 3 en 3.

Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regresa nada.



In [15]:
arr[::3]

array([1, 4, 7])

In [16]:
#Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.
arr[-1]

9

In [18]:
arr[-3:]

array([7, 8, 9])

###Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.

In [19]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
#Para acceder a los valores entre filas y columnas.
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])